export const inputElement = document.querySelector('.addTask__input');
export const addBtn = document.querySelector('.addTask__button');
export const taskList = document.querySelector('.taskList__list');
export const filterBtns = document.querySelectorAll('.listOptions__filter');
export const counterBtn = document.querySelector('.listOptions__counter');
export const clearBtn = document.querySelector('.listOptions__deleteButton');
export const dragDropMessage = document.querySelector('.dragDropMessage');
export const checkBtns = () => document.querySelectorAll('.taskList__checkbox');
export const deleteBtns = () => document.querySelectorAll('.taskList__deleteIcon');
export const tasks = () => document.querySelectorAll('.taskList__taskContent');
